### ISSUE TITLE
AutoBackup not working on HA Core since HA 2025.1

### ISSUE THREAD

**Issue by MatteoR23** [jcwillox/hass-auto-backup#178]
### The problem

Every backup fails with HA 2025.1, since backup back-end has been changed from scratch

### What version of Auto Backup has the issue?

1.5.3

### What version of Home Assistant are you running?

Home Assistant 2025.1.0

### What type of installation are you running?

Home Assistant Core

**Comment by h3x89** [comment]
### Additional Information: AutoBackup Failing on HA 2025.1

I am experiencing the same issue as described in this thread after updating Home Assistant to version **2025.1.0**. Below are the details of my setup and relevant error logs:

#### System Information:
- **Home Assistant Version**: 2025.1.0 (Core), Frontend: 20250103.0
- **AutoBackup Version**: 1.5.3
- **Installation Type**: Home Assistant Core (Docker)

#### Error Details:
During the backup process, the following error appears in the logs:

```plaintext
Logger: custom_components.auto_backup
Source: custom_components/auto_backup/__init__.py:444
Integration: Auto Backup
Error during backup. Unable to patch `_generate_backup_contents` function.
```

Additionally, the tracebacks indicate the following errors:
1. AttributeError: `'BackupManager' object has no attribute 'remove_backup'`.
2. Several instances of `Unexpected error for call_service at pos 1`.

Full traceback details:

```plaintext
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
  await getattr(self, handler)()
...
File "/config/custom_components/auto_backup/__init__.py", line 238, in purge_backups
  if await self._purge_snapshot(slug):
File "/config/custom_components/auto_backup/handlers.py", line 232, in remove_backup
  await self._manager.remove_backup(slug)
AttributeError: 'BackupManager' object has no attribute 'remove_backup'
```

#### Steps to Reproduce:
1. Updated Home Assistant to version **2025.1.0**.
2. Attempted to create or manage backups via AutoBackup.

#### Observations:
- The issue seems related to changes in the `BackupManager` class or its related functions, as the `remove_backup` attribute appears to no longer exist.
- This might be linked to a recent overhaul of the backup backend in Home Assistant.

#### Request:
Could you please investigate compatibility between the AutoBackup integration and the updated Home Assistant backup backend? Let me know if additional logs or configurations would help!

Thank you for your support!

**Comment by jeroenterheerdt** [comment]
I'd honestly question if we still need this custom integration with the overhaul of built-in backups. I have disabled it for now to experiment with what HA offers out of the box.

**Comment by MatteoR23** [comment]
What I miss tbh are events, that I use to send a command to shell to upload backups to the cloud. I suppose that until there's no alternatives, I would appreciate to maintain this custom integration

**Comment by blacknell** [comment]
I think the generational controls offered by this addon are essential.

**Comment by jcwillox** [comment]
The implementation for HA core is a bit hacky (uses a monkey patch) so it can break with updates, but shouldn't be too hard to get working again (hopefully).

The HA OS or supervised implementation is still working.

As for if this is still needed, depends on the use case, Auto Backup is still more powerful and, importantly for me at least, supports generational backup schemes.

I think for some the internal support will be enough, and hopefully they'll continue to add more features like multiple automatic backup configurations, to support generational backups.

**Comment by jcwillox** [comment]
So, the fix was a bit more complex this time as they completely changed the backup logic in HA Core, but the new logic is much better and we no longer need any monkey patches which means the implemenation should be much more stable this time. I've still got a few more things to sort out and test but hopefully should release the fix tonight

**Comment by MatteoR23** [comment]
Thank you so much for your effort

**Comment by ilexpl01** [comment]
Hi, was the fix already implemented ? I have reloaded the integration but the isuue remains:

Logger: custom_components.auto_backup
Source: custom_components/auto_backup/__init__.py:444
integration: Auto Backup ([documentation](https://github.com/jcwillox/hass-auto-backup), [issues](https://github.com/jcwillox/hass-auto-backup/issues))
First occurred: 11:26:00 (1 occurrences)
Last logged: 11:26:00

Error during backup. Unable to patch '_generate_backup_contents' function.

**Comment by ilexpl01** [comment]
The release is not available right now:

![image](https://github.com/user-attachments/assets/d333db0b-e76e-4aa7-b7bc-a69a4d0993a3)

**Comment by ilexpl01** [comment]
Seems to be running fine :)

![image](https://github.com/user-attachments/assets/06cdb992-67a7-44c8-b4af-01e78f6b5062)

GOOD JOB !

**Comment by jcwillox** [comment]
Fantastic, thanks!

**Comment by MatteoR23** [comment]
Lovely, thank you very much ☺️
