### PR TITLE
fix: support new backup methods for homeassistant 2024.11.0

### LINKED ISSUE #160: Backups failed with BackupManager object has no attribute 'remove_backup'
### The problem

Automatic backups are no longer working with Home Assistant 2024.11.0. The automatic backup fails with `AttributeError: 'BackupManager' object has no attribute 'remove_backup'`

### What version of Auto Backup has the issue?

1.5.0

### What version of Home Assistant are you running?

Home Assistant 2024.11.0

### What type of installation are you running?

Home Assistant Core

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

```python3
2024-11-07 08:57:40.451 ERROR (MainThread) [homeassistant.components.automation.automatic_backups] While executing automation automation.automatic_backups
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 743, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1081, in _async_if_step
    await self._async_run_script(if_data["if_else"])
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1274, in _async_run_script
    result = await self._async_run_long_action(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1075, in _async_if_step
    await self._async_run_script(if_data["if_then"])
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1274, in _async_run_script
    result = await self._async_run_long_action(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auto_backup/__init__.py", line 193, in async_service_handler
    await auto_backup.async_create_backup(data)
  File "/config/custom_components/auto_backup/__init__.py", line 379, in async_create_backup
    await self.purge_backups()
  File "/config/custom_components/auto_backup/__init__.py", line 463, in purge_backups
    if await self._purge_snapshot(slug)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auto_backup/__init__.py", line 482, in _purge_snapshot
    await self._handler.remove_backup(slug)
  File "/config/custom_components/auto_backup/handlers.py", line 224, in remove_backup
    await self._manager.remove_backup(slug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BackupManager' object has no attribute 'remove_backup'
```

### Additional information

From what I could find, there were some changes to the BackupManager object in https://github.com/home-assistant/core/commit/a14cb131947dc40db41e8da747b6cf97bb3bc89b#diff-a8336d653d0b63b1809369cd73a4de8d4c88c24d2c7b2dbad6481202c56d8706L35

The methods were moved e.g. `remove_backup` to `async_remove_backup` which of course leads to these errors since the object changed.

### PR DESCRIPTION
**Pull request by ccMatrix**
Updated calls to work with changed method calles in Home Assistant 2024.11.0

fixes #160

### CODE REVIEW

**Review by new-xmon-df — APPROVED** [review]
tested in my HA 2024.10, works ok

**Comment by ccMatrix** [comment]
> tested in my HA 2024.10, works ok thanks

Thank you for testing. I wanted to make sure it works on older versions of HA as well 2024.11.0 and newer so there are no issues for users of older versions if/when this gets merged.

**Review by Xyaren — APPROVED** [review]

**Comment by Xyaren** [comment]
@jcwillox Would you please take a look ?

**Review by jcwillox — APPROVED** [review]
