### ISSUE TITLE
BackupManager object has no attribute 'remove_backup' or 'generate_backup' after updating Home Assistant to 2024.11.0

### ISSUE THREAD

**Issue by h3x89** [jcwillox/hass-auto-backup#162]
### The problem

After updating Home Assistant in Docker to version 2024.11.0, the Auto Backup integration is failing during automatic backups. Previously, the integration worked without issues for a long time. The error logs indicate that the BackupManager object is missing attributes, specifically remove_backup and generate_backup, which are essential for the integration to function correctly.

### What version of Auto Backup has the issue?

v,1.5.0

### What version of Home Assistant are you running?

Home Assistant 2024.11.0 (Core) Frontend: 20241106.0

### What type of installation are you running?

Home Assistant Container

### Example YAML snippet

```yml
alias: "[ System AB ] Automatic Backups"
description: ""
use_blueprint:
  path: jcwillox/automatic_backups.yaml
  input:
    enable_hourly: true
    use_action_hourly: false
    backup_action:
      - action: auto_backup.backup
        data:
          name: "{{ name }}"
          password: "{{ password }}"
          keep_days: "{{ keep_days }}"
          include_folders:
            - config
      - metadata: {}
        data:
          message: "Backup created "
        enabled: false
        action: persistent_notification.create
      - data: {}
        enabled: false
        action: auto_backup.purge
    backup_name: |-
      {# {{ backup_type | title }}Backup: {{
        now().strftime(
          "%A, "
          ~ iif(backup_type == "hourly", "%-I:%M %p, ", "")
          ~ "%B %-d, %Y"
        )
      }}
      #}

      {# HourlyBackup: Monday, 3:04 PM, January 2, 2006 #}
      {# DailyBackup: Monday, January 2, 2006 #}

      {#
      Backup: {{
        now().strftime(
          "%A, %-I:%M %p, %Y.%m"
        )
      }}, {{ states('sensor.current_version') 
      }}, {{ backup_type | title }}
      #}

      Backup: {{
        now().strftime("%Y.%m.%d %H:%M")
      }}, {{ states('sensor.current_version') 
      }}, {{ backup_type | title }}
```

### Anything in the logs that might be useful for us?

```python3
Logger: homeassistant.components.automation.automatic_backups
Source: components/automation/__init__.py:743
Integration: Automation
Error during backup. 'BackupManager' object has no attribute 'remove_backup'

Additional error stack traces indicating 'BackupManager' object has no attribute 'generate_backup' and deprecation warnings for is_hassio.
```

### Additional information

This issue started after updating Home Assistant to version 2024.11.0. It seems related to missing attributes in the Auto Backup integration’s BackupManager class. This might be a compatibility issue with the new Home Assistant version.

**Comment by ccMatrix** [comment]
Looks like a duplicate of #160. I have a pull request with a fix you can apply if you want to test it and give feedback on the PR.

**Comment by jcwillox** [comment]
Yep duplicate of 160, which has been fixed now 👍
